/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manejoestudiantes;

import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author mi pc
 */
public class vista extends javax.swing.JFrame {

    matricula matr;

    int contadorEst = 0;
    int contador2 = 0;

    /**
     * Creates new form vista
     */
    public vista() {
        initComponents();
        asignarSemestre();
        PanelRegistroMateria.setVisible(false);
        PanelRegistroNotas.setVisible(false);
        consultaPanel.setVisible(false);
        consultaUno.setVisible(false);
        consultaDos.setVisible(false);
        consultaTres.setVisible(false);
    }

    private void asignarSemestre() {
        for (int i = 1; i <= 10; i++) {
            semestre.addItem(String.valueOf(i));
        }
    }

    private void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    private void limpiarRegistroEst() {
        cod.setText("");
        name.setText("");
        carr.setText("");
        tel.setText("");
        email.setText("");
    }

    private void limpiarNotas() {
        materia.setText("");
    }

    private void limpiarCalificaciones() {
        notaUno.setText("");
        notaDos.setText("");
        notaTres.setText("");
    }

    private void agregarMateriaComboBox(String item, JComboBox comboBox) {

        boolean materiaExistente = false;

        for (int i = 0; i < comboBox.getItemCount(); i++) {
            if (comboBox.getItemAt(i).equals(item)) {
                materiaExistente = true;
                break;
            }
        }

        if (materiaExistente == false) {
            comboBox.addItem(item);
        }
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PanelRegistro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        carr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        fechaNacimiento = new com.toedter.calendar.JDateChooser();
        matricular = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        PanelRegistroNotas = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        codEstN = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        notaUno = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        notaDos = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        notaTres = new javax.swing.JTextField();
        RegNota = new javax.swing.JButton();
        buscarMateria = new javax.swing.JButton();
        ComboMateria = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        continuar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tamano = new javax.swing.JTextField();
        asignar = new javax.swing.JButton();
        PanelRegistroMateria = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        comboCodigos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        materia = new javax.swing.JTextField();
        registrar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        semestre = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        consultaPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        consultaUno = new javax.swing.JPanel();
        codConsulta = new javax.swing.JComboBox<>();
        consultarMaterias = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaUno = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        consultaTres = new javax.swing.JPanel();
        materiaConsulta = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        EstudianteNotaFinal = new javax.swing.JButton();
        promedioGeneral = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaTres = new javax.swing.JTextArea();
        consultaDos = new javax.swing.JPanel();
        mejorNota = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaDos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(60, 211, 75));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 270, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Estudiantes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 730, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelRegistro.setBackground(new java.awt.Color(60, 211, 75));
        PanelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Codigo:");
        PanelRegistro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cod.setForeground(new java.awt.Color(0, 0, 0));
        PanelRegistro.add(cod, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 10, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre:");
        PanelRegistro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        PanelRegistro.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Sexo");
        PanelRegistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Carrera:");
        PanelRegistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        carr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        carr.setForeground(new java.awt.Color(0, 0, 0));
        PanelRegistro.add(carr, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Telefono:");
        PanelRegistro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        tel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tel.setForeground(new java.awt.Color(0, 0, 0));
        PanelRegistro.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 80, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Correo:");
        PanelRegistro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        PanelRegistro.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 80, -1));

        masculino.setBackground(new java.awt.Color(60, 211, 75));
        buttonGroup1.add(masculino);
        masculino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        masculino.setForeground(new java.awt.Color(0, 0, 0));
        masculino.setText("Masculino");
        PanelRegistro.add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        femenino.setBackground(new java.awt.Color(60, 211, 75));
        buttonGroup1.add(femenino);
        femenino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        femenino.setForeground(new java.awt.Color(0, 0, 0));
        femenino.setText("Femenino");
        PanelRegistro.add(femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("F.Nacimiento:");
        PanelRegistro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));
        PanelRegistro.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 100, -1));

        matricular.setForeground(new java.awt.Color(0, 0, 0));
        matricular.setText("Matricular");
        matricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricularActionPerformed(evt);
            }
        });
        PanelRegistro.add(matricular, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("-->");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        PanelRegistro.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 60, -1));

        jPanel2.add(PanelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 730, 90));

        PanelRegistroNotas.setBackground(new java.awt.Color(60, 211, 75));
        PanelRegistroNotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Registro de Notas");
        PanelRegistroNotas.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Materia:");
        PanelRegistroNotas.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Codigo Estudiante:");
        PanelRegistroNotas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        codEstN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        codEstN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Elija un Codigo->" }));
        PanelRegistroNotas.add(codEstN, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 140, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Nota 1:");
        PanelRegistroNotas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        PanelRegistroNotas.add(notaUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 90, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Nota 2:");
        PanelRegistroNotas.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));
        PanelRegistroNotas.add(notaDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 90, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Nota 3:");
        PanelRegistroNotas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));
        PanelRegistroNotas.add(notaTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 90, -1));

        RegNota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RegNota.setForeground(new java.awt.Color(0, 0, 0));
        RegNota.setText("Guardar");
        RegNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegNotaActionPerformed(evt);
            }
        });
        PanelRegistroNotas.add(RegNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        buscarMateria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buscarMateria.setForeground(new java.awt.Color(0, 0, 0));
        buscarMateria.setText("Buscar");
        buscarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMateriaActionPerformed(evt);
            }
        });
        PanelRegistroNotas.add(buscarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        ComboMateria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ComboMateria.setForeground(new java.awt.Color(0, 0, 0));
        PanelRegistroNotas.add(ComboMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        PanelRegistroNotas.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 240, 10));

        continuar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        continuar.setForeground(new java.awt.Color(0, 0, 0));
        continuar.setText("Consultar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });
        PanelRegistroNotas.add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jPanel2.add(PanelRegistroNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 730, 260));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("No. Estudiantes:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));
        jPanel2.add(tamano, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 80, -1));

        asignar.setText("Asignar");
        asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarActionPerformed(evt);
            }
        });
        jPanel2.add(asignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        PanelRegistroMateria.setBackground(new java.awt.Color(255, 255, 255));
        PanelRegistroMateria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        PanelRegistroMateria.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 240, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Registro de Materias");
        PanelRegistroMateria.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 730, -1));

        comboCodigos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboCodigos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Elija un Codigo->" }));
        comboCodigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCodigosActionPerformed(evt);
            }
        });
        PanelRegistroMateria.add(comboCodigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Codigo Estudiante");
        PanelRegistroMateria.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nombre de la Materia");
        PanelRegistroMateria.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        materia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PanelRegistroMateria.add(materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 140, -1));

        registrar.setForeground(new java.awt.Color(0, 0, 0));
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        PanelRegistroMateria.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 100, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Cant. Materias");
        PanelRegistroMateria.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Semestre");
        PanelRegistroMateria.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<-Seleccione un Semestre->" }));
        PanelRegistroMateria.add(semestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 150, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("-->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelRegistroMateria.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 60, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("6");
        PanelRegistroMateria.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 20, -1));

        jPanel2.add(PanelRegistroMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 730, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 730, 510));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/manejoestudiantes/img/PETRO-PNG.png"))); // NOI18N
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 730, 190));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(60, 211, 75));
        salir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(0, 0, 0));
        salir.setText("X");
        salir.setBorder(null);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel4.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 50, 50));

        consultaPanel.setBackground(new java.awt.Color(60, 211, 75));
        consultaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Consulta de Estudiantes");
        consultaPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        consultaPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 260, 10));

        jPanel4.add(consultaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 70));

        consultaUno.setBackground(new java.awt.Color(60, 211, 75));
        consultaUno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codConsulta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        consultaUno.add(codConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, -1));

        consultarMaterias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        consultarMaterias.setForeground(new java.awt.Color(0, 0, 0));
        consultarMaterias.setText("Consultar Materias");
        consultarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarMateriasActionPerformed(evt);
            }
        });
        consultaUno.add(consultarMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        areaUno.setColumns(20);
        areaUno.setRows(5);
        jScrollPane1.setViewportView(areaUno);

        consultaUno.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 350, 180));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Código:");
        consultaUno.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jPanel4.add(consultaUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 640, 210));

        consultaTres.setBackground(new java.awt.Color(60, 211, 75));
        consultaTres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        materiaConsulta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        consultaTres.add(materiaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Materia:");
        consultaTres.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        EstudianteNotaFinal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EstudianteNotaFinal.setForeground(new java.awt.Color(0, 0, 0));
        EstudianteNotaFinal.setText("Estudiante y Nota Final");
        EstudianteNotaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteNotaFinalActionPerformed(evt);
            }
        });
        consultaTres.add(EstudianteNotaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        promedioGeneral.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        promedioGeneral.setForeground(new java.awt.Color(0, 0, 0));
        promedioGeneral.setText("Promedio General");
        promedioGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedioGeneralActionPerformed(evt);
            }
        });
        consultaTres.add(promedioGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        areaTres.setColumns(20);
        areaTres.setRows(5);
        jScrollPane3.setViewportView(areaTres);

        consultaTres.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 350, 160));

        jPanel4.add(consultaTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 640, 190));

        consultaDos.setBackground(new java.awt.Color(255, 255, 255));
        consultaDos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mejorNota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mejorNota.setForeground(new java.awt.Color(0, 0, 0));
        mejorNota.setText("Consultar Mejor Nota");
        mejorNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejorNotaActionPerformed(evt);
            }
        });
        consultaDos.add(mejorNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        areaDos.setColumns(20);
        areaDos.setRows(5);
        jScrollPane2.setViewportView(areaDos);

        consultaDos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 350, 200));

        jPanel4.add(consultaDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 640, 260));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 640, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        PanelRegistroMateria.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PanelRegistroNotas.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void matricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricularActionPerformed
        // matricular el estudiante, guardar en los arreglos
        if (contadorEst < matr.getCantEstudiantes()) {
            try {
                estudiantes est = new estudiantes();

                String codigo = cod.getText();
                est.setCodigoEstudiante(codigo);

                String nombre = name.getText();
                est.setNombre(nombre);

                Date fdn = fechaNacimiento.getDate();
                est.setFechaDeNacimiento(fdn);

                String sex;
                if (masculino.isSelected()) {
                    sex = "Masculino";
                } else {
                    sex = "Femenino";
                }
                est.setSexo(sex);

                String carrera = carr.getText();
                est.setSexo(sex);

                String telefono = tel.getText();
                est.setTelefono(telefono);

                String correo = email.getText();
                est.setCorreo(correo);

                matr.setEstudiantes(est, contadorEst);

                comboCodigos.addItem(codigo);

                contadorEst++;

                limpiarRegistroEst();

            } catch (Exception e) {
                mensajeError("Complete los campos para continuar");
            }
        } else {
            mensajeError("El arreglo se encuentra lleno");
        }
    }//GEN-LAST:event_matricularActionPerformed

    private void asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarActionPerformed
        // Asignar tamaño para el arreglo de objeto
        try {
            int tam = Integer.parseInt(tamano.getText());
            matr = new matricula(tam);
            asignar.setEnabled(false);
            tamano.setEnabled(false);
        } catch (Exception e) {
            mensajeError("Complete Primero este campo");
        }
    }//GEN-LAST:event_asignarActionPerformed

    private void comboCodigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCodigosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCodigosActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        // registrar la materia del estudiante con su codigo
        if (contador2 < matr.getCantMaterias()) {
            try {
                String codigoEst = comboCodigos.getSelectedItem().toString();
                String semester = semestre.getSelectedItem().toString();
                String matery = materia.getText();

                materias mat = new materias();

                mat.setCodigoEstudiante(codigoEst);
                mat.setSemestre(semester);
                mat.setMateria(matery);

                agregarMateriaComboBox(matery, ComboMateria);
                agregarMateriaComboBox(matery, materiaConsulta);

                matr.setMaterias(mat, contador2);

                contador2++;
                limpiarNotas();

            } catch (Exception e) {
                mensajeError("Complete los campos para continuar" + e);
            }

        } else {
            mensajeError("Cantidad de Materias completadas");
        }
    }//GEN-LAST:event_registrarActionPerformed

    private void RegNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegNotaActionPerformed
        try {
            String materia = ComboMateria.getSelectedItem().toString();
            String codigoEst = codEstN.getSelectedItem().toString();

            int PosMat = matr.obtenerPosicionMateria(codigoEst, materia);

            float nota1 = Float.parseFloat(notaUno.getText());
            float nota2 = Float.parseFloat(notaDos.getText());
            float nota3 = Float.parseFloat(notaTres.getText());

            materias materiaEncontrada = matr.getArregloMaterias(PosMat);

            materiaEncontrada.setNota1(nota1);
            materiaEncontrada.setNota2(nota2);
            materiaEncontrada.setNota3(nota3);

            limpiarCalificaciones();

        } catch (Exception e) {
            mensajeError("Completa los campos para guardar la nota!");
        }

    }//GEN-LAST:event_RegNotaActionPerformed

    private void buscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMateriaActionPerformed
        //Buscamos por Materia el codigo del estudiante para asignarle las tres notas
        codEstN.removeAllItems();
        try {
            for (int i = 0; i < matr.getCantMaterias(); i++) {
                if (matr.getArregloMaterias(i) == null) {
                    continue;
                }
                if ((ComboMateria.getSelectedItem().toString()).equals(matr.getArregloMaterias(i).getMateria())) {
                    codEstN.addItem(matr.getArregloMaterias(i).getCodigoEstudiante());
                    codConsulta.addItem(matr.getArregloEstudiantes(i).getCodigoEstudiante());
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_buscarMateriaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        consultaPanel.setVisible(true);
        consultaUno.setVisible(true);
        consultaDos.setVisible(true);
        consultaTres.setVisible(true);
    }//GEN-LAST:event_continuarActionPerformed

    private void consultarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarMateriasActionPerformed
        //Consultar la materia y las nota del estudiante con su promedio del corte
        areaUno.setText("");
        //try {
            for (int i = 0; i < matr.getCantMaterias(); i++) {

                if (matr.getArregloMaterias(i) == null) {
                    continue;
                }

                if ((codConsulta.getSelectedItem().toString()).equals(matr.getArregloMaterias(i).getCodigoEstudiante())) {
                    areaUno.append("-> Materia: " + matr.getArregloMaterias(i).getMateria() + "\n"
                            + "- Nota 1: " + matr.getArregloMaterias(i).getNota1() + "\n"
                            + "- Nota 2: " + matr.getArregloMaterias(i).getNota2() + "\n"
                            + "- Nota 3: " + matr.getArregloMaterias(i).getNota3() + "\n"
                            + "Corte: "    + matr.getArregloMaterias(i).calcNotaFinal() + "\n");
                }
            }

//        } catch (Exception e) {
//            System.out.println(e);
//        }
    }//GEN-LAST:event_consultarMateriasActionPerformed

    private void mejorNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejorNotaActionPerformed
        //Consultar mejor nota
        float nota = 0;
        int buscando = 0;
        String name = "";
        String matery = "";
        try {
            for (int i = 0; i < matr.getCantMaterias(); i++) {

                if (matr.getArregloMaterias(i) == null) {
                    continue;
                }

                if (nota < matr.getArregloMaterias(i).calcNotaFinal()) {

                    matery = matr.getArregloMaterias(i).getMateria();
                    buscando = matr.buscarEstudiante(matr.getArregloMaterias(i).getCodigoEstudiante());
                    name = matr.getArregloEstudiantes(buscando).getNombre();
                    nota = matr.getArregloMaterias(i).calcNotaFinal();

                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        areaDos.append("-> Materia: " + matery + "\n"
                + "- Nombre: " + name + "\n"
                + "- Nota mas alta: " + nota + "\n");
    }//GEN-LAST:event_mejorNotaActionPerformed

    private void EstudianteNotaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteNotaFinalActionPerformed
        //Consultamos el nombre del estudiante y en cuanto le quedo el corte
        areaTres.setText("");

        try {
            for (int i = 0; i < matr.getCantMaterias(); i++) {

                if (matr.getArregloMaterias(i) == null) {
                    continue;
                }

                if ((materiaConsulta.getSelectedItem().toString()).equals(matr.getArregloMaterias(i).getMateria())) {

                    int buscando = matr.buscarEstudiante(matr.getArregloMaterias(i).getCodigoEstudiante());
                    estudiantes est = matr.getArregloEstudiantes(buscando);

                    areaTres.append("-> Nombre del Estudiante: " + est.getNombre() + "\n"
                            + "- Corte: " + matr.getArregloMaterias(i).calcNotaFinal() + "\n");
                }

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_EstudianteNotaFinalActionPerformed

    private void promedioGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promedioGeneralActionPerformed
        //Consulta el promedio general
        areaTres.setText("");
        float nota = 0;
        int numEst = 0;
        float promedio = 0;
        try {

            for (int i = 0; i < matr.getCantMaterias(); i++) {
                if (matr.getArregloMaterias(i) == null) {
                    continue;
                }

                if ((materiaConsulta.getSelectedItem().toString()).equals(matr.getArregloMaterias(i).getMateria())) {
                    nota += matr.getArregloMaterias(i).calcNotaFinal();
                    numEst++;

                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }
        promedio = nota / numEst;
        areaTres.append("Materia: " + materiaConsulta.getSelectedItem().toString() + "\n"
                + "Promedio General: " + promedio + "\n");


    }//GEN-LAST:event_promedioGeneralActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboMateria;
    private javax.swing.JButton EstudianteNotaFinal;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JPanel PanelRegistroMateria;
    private javax.swing.JPanel PanelRegistroNotas;
    private javax.swing.JButton RegNota;
    private javax.swing.JTextArea areaDos;
    private javax.swing.JTextArea areaTres;
    private javax.swing.JTextArea areaUno;
    private javax.swing.JButton asignar;
    private javax.swing.JButton buscarMateria;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField carr;
    private javax.swing.JTextField cod;
    private javax.swing.JComboBox<String> codConsulta;
    private javax.swing.JComboBox<String> codEstN;
    private javax.swing.JComboBox<String> comboCodigos;
    private javax.swing.JPanel consultaDos;
    private javax.swing.JPanel consultaPanel;
    private javax.swing.JPanel consultaTres;
    private javax.swing.JPanel consultaUno;
    private javax.swing.JButton consultarMaterias;
    private javax.swing.JButton continuar;
    private javax.swing.JTextField email;
    private com.toedter.calendar.JDateChooser fechaNacimiento;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField materia;
    private javax.swing.JComboBox<String> materiaConsulta;
    private javax.swing.JButton matricular;
    private javax.swing.JButton mejorNota;
    private javax.swing.JTextField name;
    private javax.swing.JTextField notaDos;
    private javax.swing.JTextField notaTres;
    private javax.swing.JTextField notaUno;
    private javax.swing.JButton promedioGeneral;
    private javax.swing.JButton registrar;
    private javax.swing.JButton salir;
    private javax.swing.JComboBox<String> semestre;
    private javax.swing.JTextField tamano;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
