/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco;

import javax.swing.JOptionPane;

/**
 *
 * @author Andrés Suarez
 */
public class login extends javax.swing.JFrame {

    private adminView adminview; 
    
    administrador baseDeDatos;

    /**
     * Creates new form vista
     */
    public login(administrador admin, adminView adminview) {
        initComponents();
        this.baseDeDatos = admin;
        this.adminview = adminview;
    }

    public void initWindow() {
        setVisible(true);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void mensajePanel(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordAdmin = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        contraseñaUsuario = new javax.swing.JTextField();
        userAdmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        botonAdmin = new javax.swing.JButton();
        botonUsuario = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 10, 300));

        jPanel2.setBackground(new java.awt.Color(64, 154, 243));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Iniciar Sesión");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banco/images/setting_icon_224607.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 70, -1));

        passwordAdmin.setBackground(new java.awt.Color(255, 255, 255));
        passwordAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordAdmin.setForeground(new java.awt.Color(0, 0, 0));
        passwordAdmin.setBorder(null);
        jPanel1.add(passwordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 120, 20));

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usuario.setForeground(new java.awt.Color(0, 0, 0));
        usuario.setBorder(null);
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 120, 20));

        contraseñaUsuario.setBackground(new java.awt.Color(255, 255, 255));
        contraseñaUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contraseñaUsuario.setForeground(new java.awt.Color(0, 0, 0));
        contraseñaUsuario.setBorder(null);
        jPanel1.add(contraseñaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 120, 20));

        userAdmin.setBackground(new java.awt.Color(255, 255, 255));
        userAdmin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        userAdmin.setForeground(new java.awt.Color(0, 0, 0));
        userAdmin.setBorder(null);
        userAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                userAdminFocusLost(evt);
            }
        });
        jPanel1.add(userAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 120, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Contraseña");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Usuario");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banco/images/user_icon_224512.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 70, 80));

        botonAdmin.setBackground(new java.awt.Color(64, 154, 243));
        botonAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banco/images/arrow_right_icon_224518.png"))); // NOI18N
        botonAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminActionPerformed(evt);
            }
        });
        jPanel1.add(botonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, 30));

        botonUsuario.setBackground(new java.awt.Color(64, 154, 243));
        botonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banco/images/arrow_right_icon_224518.png"))); // NOI18N
        botonUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 120, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 120, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 120, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 120, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userAdminFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_userAdminFocusLost

    private void botonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminActionPerformed

        String user = userAdmin.getText();
        String password = passwordAdmin.getText();

        if (user.equals("admin") && password.equals("superadmin")) {
            mensajePanel("Inicio de sesion correcto");

            this.setVisible(false);

            adminview.setVisible(true);
            adminview.setResizable(false);
            adminview.setLocationRelativeTo(null);

        } else {
            mensajePanel("Usuario y contraseña incorrectos");
        }
    }//GEN-LAST:event_botonAdminActionPerformed

    private void botonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioActionPerformed
//        try {
//            for (int i = 0; i < baseDeDatos.getCantClientes(); i++) {
//                
//                if (usuario.getText().equals(baseDeDatos.getArregloDeClientes(i).getIdentificacion()) && contraseñaUsuario.getText().equals(baseDeDatos.getArregloDeClientes(i).getContaseña())) {
//                    mensajePanel("Inicio de sesión correcto");
//                    this.setVisible(false);
//
//                    clientView vistaCliente = new clientView(baseDeDatos);
//                    vistaCliente.setVisible(true);
//                    vistaCliente.setResizable(false);
//                    vistaCliente.setLocationRelativeTo(null);
//                    
//                    break;
//                } else {
//                    mensajePanel("Usuario y/o contraseña incorrectos");
//                }
//            }
//        } catch (Exception e) {
//            mensajePanel("Complete los campos");
//        }
    }//GEN-LAST:event_botonUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAdmin;
    public javax.swing.JButton botonUsuario;
    public javax.swing.JTextField contraseñaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField passwordAdmin;
    private javax.swing.JTextField userAdmin;
    public javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
